### PR TITLE
Add get pages in range for Android and IOS

### PR DESCRIPTION
**Pull request by CabraKill**
## Changes: 🌟
* Add the new feature to the Flutter common lib files
* Add the new feature to the Android implementation
* Add the new feature to the IOS implementation
* Update the example page to have the new feature button

## Warning ☢️: 
The android folder, and perhaps the ios folder, need to be migrated to Embedding V2 in order to able to run the example. Those changes can be done just by deleting those folders and executing 
```bash
flutter create .
```
Those changes were not included to simplify the amount of changes in the PR. If this fix would be nice I can commit those changes 😉

### CODE REVIEW

**Comment by thevikke** [comment]
Hey, I had a look at the code it looks good. Can you push the Embedding V2 changes if you have them? I will test the package on iOS and Android, and then if nothing goes wrong, I approve.

**Comment by CabraKill** [comment]
> Hey, I had a look at the code it looks good. Can you push the Embedding V2 changes if you have them? I will test the package on iOS and Android, and then if nothing goes wrong, I approve.

I've made a new commit with the necessary changes to run the application in Android and Ios. Let me know if you can't test the app or need something else.

**Comment by thevikke** [comment]
Tested with Android. It seems that the range function works, but the paginated function (old) has broken. At least on my emulator. I did a test running with the original package (master) with v2 embedding, and in that version, the pagination worked. I'm guessing there is something wrong with the Android code that you submitted. I didn't have time to investigate this week as I'm going to a wedding for the weekend. But I included the pdf I tested with as well as the error message to this post. 

Haven't been able to run in on iOS yet. Will try next week.

### Error message
```
Connecting to VM Service at ws://127.0.0.1:55147/wW0YYxLSdYM=/ws
D/EGL_emulation( 7535): eglMakeCurrent: 0xdd615ce0: ver 3 1 (tinfo 0xc91da980)
I/zygote  ( 7535): Do partial code cache collection, code=16KB, data=19KB
I/zygote  ( 7535): After code cache collection, code=16KB, data=19KB
I/zygote  ( 7535): Increasing code cache capacity to 128KB
D/EGL_emulation( 7535): eglMakeCurrent: 0xdd905900: ver 3 1 (tinfo 0xc91daa30)
D/FilePickerUtils( 7535): Allowed file extensions mimes: [application/pdf]
D/FilePickerDelegate( 7535): Selected type */*
D/EGL_emulation( 7535): eglMakeCurrent: 0xdd905900: ver 3 1 (tinfo 0xc91daa30)
I/FilePickerUtils( 7535): Caching from URI: content://com.android.providers.downloads.documents/document/39
D/FilePickerUtils( 7535): File loaded and cached at:/data/user/0/com.example.example/cache/file_picker/sample.pdf
D/FilePickerDelegate( 7535): File path:[com.mr.flutter.plugin.filepicker.FileInfo@b125a23]
2
D/EGL_emulation( 7535): eglMakeCurrent: 0xdd615ce0: ver 3 1 (tinfo 0xc91da980)
D/EGL_emulation( 7535): eglMakeCurrent: 0xdd905900: ver 3 1 (tinfo 0xc91daa30)
E/AndroidRuntime( 7535): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime( 7535): Process: com.example.example, PID: 7535
E/AndroidRuntime( 7535): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 7535): 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
E/AndroidRuntime( 7535): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 7535): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 7535): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 7535): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime( 7535): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime( 7535): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime( 7535): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime( 7535): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
E/AndroidRuntime( 7535): 	at com.example.read_pdf_text.ReadPdfTextPlugin$PaginatePDFAsyncTask.doInBackground(ReadPdfTextPlugin.java:214)
E/AndroidRuntime( 7535): 	at com.example.read_pdf_text.ReadPdfTextPlugin$PaginatePDFAsyncTask.doInBackground(ReadPdfTextPlugin.java:197)
E/AndroidRuntime( 7535): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime( 7535): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 7535): 	... 4 more
D/EGL_emulation( 7535): eglMakeCurrent: 0xdd905900: ver 3 1 (tinfo 0xc91daa30)
I/zygote  ( 7535): Do partial code cache collection, code=61KB, data=50KB
I/zygote  ( 7535): After code cache collection, code=61KB, data=50KB
I/zygote  ( 7535): Increasing code cache capacity to 256KB
D/EGL_emulation( 7535): eglMakeCurrent: 0xdd615ce0: ver 3 1 (tinfo 0xc91da980)
Lost connection to device.
```

### Pdf test file
[sample.pdf](https://github.com/thevikke/read_pdf_text/files/12752556/sample.pdf)

### Image
image

**Comment by CabraKill** [comment]
Oh! Thank you for the info. I didn't know about that. I'll analyze and push a fix for Android and IOS asap!

**Comment by thevikke** [comment]
Got the iOS version finally working (had to install a new version of Xcode, and that required a new version of MacOS 💯), but it breaks when trying to get the range from PDF. With error:
```
read_pdf_text/SwiftReadPdfTextPlugin.swift:78: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Lost connection to device.
```
I run it with Simulator iPhone 15 Pro Max and iOS 17.0.

**Pull request closed without merging**
